# Generated by Django 6.0.2 on 2026-10-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('common', '0012_device_neutral_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.device'),
        ),
        migrations.CreateModel(
            name='RequestNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('certificate_id', 'nonce'), name='unique_device_request_nonce')],
            },
        ),
    ]
