# Generated by Django 6.0.2 on 2026-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentsession_device_requestnonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='fingerprint_challenge',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='fingerprint_challenge_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
