# Generated by Django 6.0.2 on 2026-02-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
