# Generated by Django 6.0.2 on 2026-02-12 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_organization_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='accesslogs',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='biometricface',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='biometricfingerprint',
            name='organization',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricface',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricface',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biometricfingerprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricfingerprint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='device_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.roles'),
        ),
        migrations.AlterField(
            model_name='biometricface',
            name='embedding',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='biometricface',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='common.users'),
        ),
        migrations.AlterField(
            model_name='biometricfingerprint',
            name='embedding',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='biometricfingerprint',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='common.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='devices',
            unique_together={('organization', 'pc_id')},
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('organization', 'username')},
        ),
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['user', '-timestamp'], name='common_acce_user_id_929c81_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['device', '-timestamp'], name='common_acce_device__3c91f8_idx'),
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
