# Generated by Django 6.0.2 on 2026-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintsession',
            name='challenge',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
