# Generated by Django 6.0.2 on 2026-03-21 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_biometricface_source_alter_biometricface_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricface',
            name='source',
        ),
        migrations.AddField(
            model_name='biometricfingerprint',
            name='source',
            field=models.CharField(default='scanner', max_length=30),
        ),
        migrations.AlterField(
            model_name='biometricface',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='common.users'),
        ),
        migrations.AlterField(
            model_name='biometricfingerprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='common.users'),
        ),
    ]
