# Generated by Django 6.0.2 on 2026-02-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_userroles_organization_remove_userroles_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='creted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
