# Generated by Django 6.0.2 on 2026-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_biometricface_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricfingerprint',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('phone', 'Phone'), ('scanner', 'Scanner'), ('external', 'External')], default='manual', max_length=20),
        ),
    ]
