# Generated by Django 6.0.2 on 2026-03-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_biometricfingerprint_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricface',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='common.users'),
        ),
    ]
