# Generated by Django 6.0.2 on 2026-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_users_creted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
