# Generated by Django 6.0.2 on 2026-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_biometricface_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricfingerprint',
            name='credential_id',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricfingerprint',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricfingerprint',
            name='sign_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricfingerprint',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
