# Generated by Django 6.0.2 on 2026-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_adminuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='organization',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='admin_users', to='common.organization'),
        ),
    ]
