# Generated by Django 6.0.2 on 2026-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_biometricfingerprint_credential_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricfingerprint',
            name='challenge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
