# Generated by Django 6.0.2 on 2026-04-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_biometricfingerprint_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricfingerprint',
            name='challenge',
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(db_index=True, max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('cert', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('device_public_key', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='common.organization')),
            ],
            options={
                'unique_together': {('organization', 'pc_id')},
            },
        ),
        migrations.AlterField(
            model_name='accesslogs',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.device'),
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
