# Generated by Django 6.0.2 on 2026-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_roles_created_at_roles_created_by_roles_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, related_name='admin_users', to='common.organization'),
        ),
    ]
