# Generated by Django 6.0.2 on 2026-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_device_neutral_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricfingerprint',
            name='rp_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biometricfingerprint',
            name='credential_id',
            field=models.BinaryField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='biometricfingerprint',
            name='sign_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
