# Generated by Django 6.0.2 on 2026-04-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0008_remove_biometricfingerprint_challenge_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_tokens', to='common.organization')),
            ],
        ),
    ]
